package:
  name: workerbee
  version: {{ environ['CONDACI_VERSION'] }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0       # [py2k]
    - psycopg2 >=2.6
    - postgres >=2.2
    - docopt >=0.6
    - arrow >=0.7

test:

  imports:
    - workerbee
    - workerbee.postgresql
    - workerbee.filesystem

about:
  home: https://github.com/menpo/workerbee/
  license: BSD
